[project]
name = "data-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Tim", email = "Tymotei.Polianskyi@lnu.edu.ua" }
]
requires-python = ">=3.14"
dependencies = [
    "jupyterlab>=4.6.3",
    "matplotlib>=3.11.2",
    "pandas>=3.0.6",
]

[project.scripts]
data-engineering = "data_engineering:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
